# Generated by Django 5.1.5 on 2025-01-28 01:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=150, null=True, verbose_name='Car Model')),
                ('year', models.IntegerField(default=0, verbose_name='Year Car')),
                ('patent', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Formato Patente Incorrecto.', regex='/^[A-Z]{3}\\d{3}$/')], verbose_name='Patent')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garage.brand', verbose_name='Brand')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garage.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['id'],
            },
        ),
    ]
