# Generated by Django 5.1.5 on 2025-01-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_custom_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='car',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Custom',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
