# Generated by Django 5.1.5 on 2025-01-29 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_remove_car_brand_remove_car_cat_delete_custom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
