# Generated by Django 5.1.5 on 2025-01-29 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0007_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Nombre')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garage.brand', verbose_name='Brand')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garage.category', verbose_name='Category')),
            ],
        ),
    ]
